name: 🚀 Publish

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: 🚀 Publish NuGet
      uses: alirezanet/publish-nuget@v3.0.0
      with:
        PROJECT_FILE_PATH: DrawnTableControl/DrawnTableControl.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
